In [1]:
#import library
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#load the dataset
dataset = pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset.shape

(399, 25)

In [9]:
dataset.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [25]:
print(dataset['rbc'].value_counts())
print(dataset['pc'].value_counts())
print(dataset['pcc'].value_counts())
print(dataset['ba'].value_counts())
print(dataset['htn'].value_counts())
print(dataset['dm'].value_counts())
print(dataset['cad'].value_counts())
print(dataset['appet'].value_counts())
print(dataset['pe'].value_counts())
print(dataset['ane'].value_counts())
print(dataset['classification'].value_counts())
print(dataset['sg'].value_counts())

rbc
1    352
0     47
Name: count, dtype: int64
pc
1    323
0     76
Name: count, dtype: int64
pcc
0    357
1     42
Name: count, dtype: int64
ba
0    377
1     22
Name: count, dtype: int64
htn
0    253
1    146
Name: count, dtype: int64
dm
0    263
1    136
Name: count, dtype: int64
cad
0    365
1     34
Name: count, dtype: int64
appet
1    316
0     83
Name: count, dtype: int64
pe
0    322
1     77
Name: count, dtype: int64
ane
0    339
1     60
Name: count, dtype: int64
classification
1    249
0    150
Name: count, dtype: int64
sg
a    152
c     84
b     81
d     75
e      7
Name: count, dtype: int64

In [32]:
#changing categorical value to numerical value
dataset = pd.get_dummies(dataset, drop_first=True)
dataset=dataset.astype(int)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_1,pcc_1,ba_1,htn_1,dm_1,cad_1,appet_1,pe_1,ane_1,classification_1
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [34]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_2', 'sg_3', 'sg_4', 'sg_5', 'rbc_1', 'pc_1', 'pcc_1',
       'ba_1', 'htn_1', 'dm_1', 'cad_1', 'appet_1', 'pe_1', 'ane_1',
       'classification_1'],
      dtype='object')

In [35]:
independent = dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_2', 'sg_3', 'sg_4', 'sg_5', 'rbc_1', 'pc_1', 'pcc_1',
       'ba_1', 'htn_1', 'dm_1', 'cad_1', 'appet_1', 'pe_1', 'ane_1']]
dependent = dataset[['classification_1']]

In [36]:
print(independent.shape)
print(dependent.shape)

(399, 27)
(399, 1)

In [37]:
#split model for training and testing
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independent, dependent, test_size=1/3, random_state=0)
X_train

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_1,pc_1,pcc_1,ba_1,htn_1,dm_1,cad_1,appet_1,pe_1,ane_1
240,60,100,0,3,263,27,1,135,4,12,...,1,1,0,0,1,1,1,1,0,0
218,57,80,0,0,120,48,1,137,4,11,...,1,1,0,0,1,1,0,1,0,0
101,42,70,0,0,75,31,1,141,3,16,...,1,1,0,0,0,0,0,1,0,0
311,66,70,1,0,248,30,1,138,5,12,...,1,1,0,0,1,1,0,1,0,0
194,55,80,0,0,146,57,3,137,4,9,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,68,70,0,0,98,86,4,135,3,9,...,1,1,0,0,1,1,1,0,1,0
192,54,90,1,0,150,18,1,140,4,12,...,1,0,0,0,0,0,0,0,1,1
117,45,80,0,0,107,15,1,141,4,11,...,1,0,0,0,0,0,0,1,0,0
47,30,80,0,0,89,42,0,139,5,16,...,1,1,0,0,0,0,0,1,0,0
172,51,60,0,0,129,25,1,139,5,17,...,1,1,0,0,0,0,0,1,0,0

In [38]:
#Model Creation
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
parameters = {'n_estimators':[10,50,100], 
              'criterion':['gini', 'entropy', 'log_loss'],# paramters are random forest from website
              'max_features':['sqrt', 'log2']}

grid = GridSearchCV(RandomForestClassifier(),parameters, refit = True, verbose =3, n_jobs=-1, scoring='f1') 
#refit true is for finding the best model,
#false will give last model
#https://scikit-learn.org/stable/modules/model_evaluation.html - for scoring 
grid.fit(X_train,Y_train) # can able to call directly without training and testing

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 50, 100]},
             scoring='f1', verbose=3)

In [39]:
print(grid.best_params_)

{'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}

In [40]:
classifier = grid.cv_results_ 
classifier
print('The value for best parameter: ',format(grid.best_params_))

The value for best parameter:  {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}

In [41]:
table = pd.DataFrame.from_dict(classifier)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.063929,0.005022,0.032326,1.643658e-03,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.970588,0.985507,0.968750,0.969697,0.985075,0.975923,0.007672,14
1,0.280256,0.005192,0.046864,5.840039e-07,gini,sqrt,50,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.969697,0.985507,0.968750,0.985075,1.000000,0.981806,0.011597,9
2,0.563086,0.017526,0.063183,9.977153e-03,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.985507,0.985507,0.968750,0.985075,0.985075,0.981983,0.006619,7
3,0.063225,0.001428,0.031018,1.314087e-03,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.939394,0.985507,0.935484,0.969697,0.969697,0.959956,0.019310,18
4,0.293529,0.006949,0.043796,1.186424e-02,gini,log2,50,"{'criterion': 'gini', 'max_features': 'log2', ...",0.985507,0.957746,0.968750,0.969697,0.985075,0.973355,0.010614,15
5,0.565371,0.014199,0.058255,9.859765e-03,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.985507,0.984615,0.969697,1.000000,0.987964,0.011320,2
6,0.066266,0.004411,0.028122,6.245662e-03,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.955224,0.985507,0.984615,0.985075,1.000000,0.982084,0.014625,5
7,0.296892,0.005570,0.037876,7.364750e-03,entropy,sqrt,50,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.985075,0.985507,0.984615,0.969697,0.985075,0.981994,0.006155,6
8,0.582920,0.017819,0.059867,2.078830e-02,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.985507,0.971429,0.968750,0.985075,0.985075,0.979167,0.007462,11
9,0.081097,0.011896,0.029352,5.397692e-03,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.985075,0.957746,0.918033,0.985075,1.000000,0.969186,0.028989,16
10,0.310922,0.011082,0.039215,6.939970e-03,entropy,log2,50,"{'criterion': 'entropy', 'max_features': 'log2...",0.985507,0.985507,0.952381,0.985075,1.000000,0.981694,0.015715,10
11,0.590223,0.016462,0.054368,7.535451e-03,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.971429,0.984615,0.985075,1.000000,0.988224,0.010792,1
12,0.073211,0.008734,0.030652,1.181126e-03,log_loss,sqrt,10,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.955224,0.985507,0.968750,0.985075,1.000000,0.978911,0.015431,13
13,0.298253,0.007214,0.042650,5.695372e-03,log_loss,sqrt,50,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.985507,0.985507,0.968750,0.985075,0.985075,0.981983,0.006619,7
14,0.562882,0.010255,0.054791,8.460440e-03,log_loss,sqrt,100,"{'criterion': 'log_loss', 'max_features': 'sqr...",1.000000,0.971429,0.968750,0.969697,0.985075,0.978990,0.012057,12
15,0.072173,0.007924,0.029751,3.021763e-03,log_loss,log2,10,"{'criterion': 'log_loss', 'max_features': 'log...",0.953846,0.957746,0.952381,0.969697,1.000000,0.966734,0.017710,17
16,0.294773,0.006611,0.040977,6.098521e-03,log_loss,log2,50,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.985507,0.968750,0.969697,1.000000,0.984791,0.013772,4
17,0.485762,0.027719,0.037543,1.281216e-02,log_loss,log2,100,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.985507,0.984615,0.969697,1.000000,0.987964,0.011320,2

In [42]:
grid_pred = grid.predict(X_test)
grid_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0])

In [43]:
#Evalution using confusion matrix
from sklearn.metrics import confusion_matrix
con_mat = confusion_matrix(Y_test,grid_pred)
con_mat

array([[51,  0],
       [ 1, 81]], dtype=int64)

In [44]:
#To create a classification report
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,grid_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [45]:
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,grid_pred,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}: 0.9924946382275899

In [46]:
from sklearn.metrics import roc_auc_score #Receiver Operating Characteristic Curve, Area Under the curve
roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1]) # to get a greater probability value, [:,1][R,C]

0.9997608799617408

In [47]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_2', 'sg_3', 'sg_4', 'sg_5', 'rbc_1', 'pc_1', 'pcc_1',
       'ba_1', 'htn_1', 'dm_1', 'cad_1', 'appet_1', 'pe_1', 'ane_1',
       'classification_1'],
      dtype='object')

In [60]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=float(input("SG_B:"))
sg_c_input=float(input("SG_C:"))
sg_d_input=float(input("SG_D:"))
sg_e_input=float(input("SG_E:"))
rbc_normal_input=float(input("RBC Normal 0 or 1:"))
pc_normal_input=float(input("PC Normal 0 or 1:"))
pcc_present_input=float(input("PC Present 0 or 1:"))
ba_present_input=float(input("BA_Present 0 or 1:"))
htn_yes_input=float(input("HTN 0 or 1:"))
dm_yes_input=float(input("DM 0 or 1:"))
cad_yes_input=float(input("CAD 0 or 1:"))
appet_yes_input=float(input("Appet 0 or 1:"))
pe_yes_input=float(input("PE 0 or 1:"))
ane_yes_input=float(input("ANE 0 or 1:"))

Age:23
BP:23
AL:45
SU:57
BGR:70
BU:89
SC:12
SOD:34
POT:65
HRMO:76
PCV:58
WC:87
RC:98
SG_B:1
SG_C:2
SG_D:3
SG_E:4
RBC Normal 0 or 1:1
PC Normal 0 or 1:0
PC Present 0 or 1:0
BA_Present 0 or 1:1
HTN 0 or 1:0
DM 0 or 1:1
CAD 0 or 1:0
Appet 0 or 1:1
PE 0 or 1:0
ANE 0 or 1:1

In [61]:
Future_Prediction=grid.predict([[age_input,bp_input, al_input, su_input, bgr_input, bu_input, sc_input, sod_input, pot_input, hrmo_input, pcv_input,
       wc_input, rc_input, sg_b_input, sg_c_input, sg_d_input, sg_e_input, rbc_normal_input, pc_normal_input,
       pcc_present_input, ba_present_input, htn_yes_input, dm_yes_input, cad_yes_input,
       appet_yes_input, pe_yes_input, ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]

C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(