In [1]:
#import library
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#load the dataset
dataset = pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [4]:
#changing categorical value to numerical value
dataset = pd.get_dummies(dataset, drop_first=True)
dataset=dataset.astype(int)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [5]:
dataset['classification_yes'].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
independent = dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent = dataset[['classification_yes']]

In [8]:
print(independent.shape)
print(dependent.shape)

(399, 27)
(399, 1)

In [9]:
#split model for training and testing
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independent, dependent, test_size=1/3, random_state=0)
X_train

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
240,60,100,0,3,263,27,1,135,4,12,...,1,1,0,0,1,1,1,1,0,0
218,57,80,0,0,120,48,1,137,4,11,...,1,1,0,0,1,1,0,1,0,0
101,42,70,0,0,75,31,1,141,3,16,...,1,1,0,0,0,0,0,1,0,0
311,66,70,1,0,248,30,1,138,5,12,...,1,1,0,0,1,1,0,1,0,0
194,55,80,0,0,146,57,3,137,4,9,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,68,70,0,0,98,86,4,135,3,9,...,1,1,0,0,1,1,1,0,1,0
192,54,90,1,0,150,18,1,140,4,12,...,1,0,0,0,0,0,0,0,1,1
117,45,80,0,0,107,15,1,141,4,11,...,1,0,0,0,0,0,0,1,0,0
47,30,80,0,0,89,42,0,139,5,16,...,1,1,0,0,0,0,0,1,0,0
172,51,60,0,0,129,25,1,139,5,17,...,1,1,0,0,0,0,0,1,0,0

In [10]:
#to develope a model
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
parameters = {'criterion': ['gini', 'entropy', 'log_loss'],
             'splitter':['best', 'random'],
             'max_features':['sqrt', 'log2']}
grid = GridSearchCV(DecisionTreeClassifier(),parameters,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [11]:
#to get the results
classifier = grid.cv_results_
classifier
print("The value of best parameter",format(grid.best_params_))

The value of best parameter {'criterion': 'log_loss', 'max_features': 'sqrt', 'splitter': 'random'}

In [12]:
#to get the result in table
table = pd.DataFrame.from_dict(classifier)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.017535,0.002642,0.027556,0.003681,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.962963,0.962264,0.981217,0.961826,0.981031,0.969860,0.009204,2
1,0.017184,0.004522,0.023349,0.006685,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.945100,0.962264,0.906705,1.000000,0.943651,0.951544,0.030256,5
2,0.014269,0.001660,0.025171,0.005894,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.963284,0.906166,0.925524,0.905155,0.962264,0.932479,0.025782,11
3,0.015681,0.009884,0.023878,0.007046,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.963284,0.943041,0.944023,0.943651,0.962573,0.951314,0.009491,6
4,0.012496,0.006248,0.025075,0.007718,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.945100,0.923510,1.000000,0.887719,0.981217,0.947509,0.040120,7
5,0.015281,0.000896,0.023900,0.008358,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.981378,0.943041,0.925524,0.924528,0.962573,0.947409,0.021934,8
6,0.016232,0.001198,0.019085,0.006141,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.945100,0.925272,0.925524,0.962264,0.924528,0.936538,0.015017,10
7,0.016360,0.002030,0.017849,0.005794,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.945100,0.981014,0.944023,0.981217,0.981217,0.966514,0.017928,3
8,0.012627,0.006328,0.024786,0.007526,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.981569,0.922185,0.907035,0.962264,0.962264,0.947064,0.027835,9
9,0.019874,0.005665,0.020190,0.009252,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",1.000000,0.943041,0.962573,0.962264,1.000000,0.973576,0.022706,1
10,0.010394,0.004386,0.027082,0.006614,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",0.890467,0.883278,0.925146,0.942332,0.981031,0.924451,0.035698,12
11,0.011938,0.004934,0.012262,0.006169,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.943699,0.925146,0.981217,0.962573,0.962527,0.026478,4

In [13]:
# to check in test data
grid_pred= grid.predict(X_test)
grid_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0])

In [14]:
#confusion matrix
from sklearn.metrics import confusion_matrix
con_mat=confusion_matrix(Y_test,grid_pred)
con_mat
#classification report
from sklearn.metrics import classification_report
class_report=classification_report(Y_test,grid_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.89      0.98      0.93        51
           1       0.99      0.93      0.96        82

    accuracy                           0.95       133
   macro avg       0.94      0.95      0.95       133
weighted avg       0.95      0.95      0.95       133

In [15]:
#f1score
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,grid_pred,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'log_loss', 'max_features': 'sqrt', 'splitter': 'random'}: 0.9477705902916346

In [16]:
#roc_auc
from sklearn.metrics import roc_auc_score
roc = roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])
roc

0.9536107125777139

In [17]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=float(input("SG_B:"))
sg_c_input=float(input("SG_C:"))
sg_d_input=float(input("SG_D:"))
sg_e_input=float(input("SG_E:"))
rbc_normal_input=float(input("RBC Normal 0 or 1:"))
pc_normal_input=float(input("PC Normal 0 or 1:"))
pcc_present_input=float(input("PC Present 0 or 1:"))
ba_present_input=float(input("BA_Present 0 or 1:"))
htn_yes_input=float(input("HTN 0 or 1:"))
dm_yes_input=float(input("DM 0 or 1:"))
cad_yes_input=float(input("CAD 0 or 1:"))
appet_yes_input=float(input("Appet 0 or 1:"))
pe_yes_input=float(input("PE 0 or 1:"))
ane_yes_input=float(input("ANE 0 or 1:"))

Age:45
BP:245
AL:456
SU:234
BGR:345
BU:34
SC:56
SOD:2
POT:3
HRMO:456
PCV:43
WC:234
RC:234
SG_B:2
SG_C:1
SG_D:3
SG_E:2
RBC Normal 0 or 1:1
PC Normal 0 or 1:1
PC Present 0 or 1:1
BA_Present 0 or 1:1
HTN 0 or 1:1
DM 0 or 1:1
CAD 0 or 1:1
Appet 0 or 1:1
PE 0 or 1:1
ANE 0 or 1:1

In [18]:
Future_Prediction=grid.predict([[age_input,bp_input, al_input, su_input, bgr_input, bu_input, sc_input, sod_input, pot_input, hrmo_input, pcv_input,
       wc_input, rc_input, sg_b_input, sg_c_input, sg_d_input, sg_e_input, rbc_normal_input, pc_normal_input,
       pcc_present_input, ba_present_input, htn_yes_input, dm_yes_input, cad_yes_input,
       appet_yes_input, pe_yes_input, ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]

C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(