In [1]:
#import library
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#load the dataset
dataset = pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
#changing categorical value to numerical value
dataset = pd.get_dummies(dataset, drop_first=True)
dataset=dataset.astype(int)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
dataset = dataset.drop(['User ID'],axis=1) # axis 1 will remove the column 1 and axis 0 will remove the row

In [5]:
# to find the purchased not purchased count
dataset['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [6]:
independent = dataset[['Age', 'EstimatedSalary','Gender_Male']]
dependent = dataset[['Purchased']]

In [7]:
#split model for training and testing
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [8]:
#Model Creation
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=10,weights='uniform',p=1.0,metric='minkowski') # Minkowski - is an standard Euclidean distance
classifier.fit(X_train,Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=10, p=1.0)

In [9]:
# to test the data
test_Pred = classifier.predict(X_test)
test_Pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1])

In [10]:
#Evalution using confusion matrix
from sklearn.metrics import confusion_matrix
con_mat = confusion_matrix(Y_test,test_Pred) # error 1 should be lesser than error 2 (i.e) good model
con_mat

array([[81,  4],
       [18, 31]], dtype=int64)

In [11]:
#Create an report 
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,test_Pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.82      0.95      0.88        85
           1       0.89      0.63      0.74        49

    accuracy                           0.84       134
   macro avg       0.85      0.79      0.81       134
weighted avg       0.84      0.84      0.83       134

Accuracy - 
        What is the percentage of correct classification to the total test input? - 63%
Recall - 
        What is the correct classification of Purchased and not purchased to the test data? - Purchased 0%, Not Purchased 100%
Precision - 
        What is the Percentage of correctly classified purchased and not purchased to the sum of correctly and wrongly classified purchased and Not purchased? Purchased - 0%, Not Purchased - 63%
F1 score - 
        What is the overall performance of purchased and Not purchased? - Purchased - 0%, Not Purchased - 78%.
Macro Avg - 
        What is the Avg of Precision, Recall, F1Score? - Precision - 32%, Recall - 50%, F1score - 39%.
Weighted Avg - 
        What is the proportion of each class(Precision, Recall, F1Score)? - Precision - 40%, Recall - 63%, F1score - 49%.

In [12]:
# id_input=int(input("Enter the UserId: "))
age_input=int(input("Enter the age: "))
Salary= int(input("Enter the salary: "))
Gender = int(input("Enter the gender: "))

Enter the age: 26
Enter the salary: 70000
Enter the gender: 0

In [13]:
classifier.predict([[age_input,Salary,Gender]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([0])

In [14]:
classifier.predict([[45,78000,1]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([0])

# Grid Search CV

In [15]:
#to develope a model
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
parameters = {'n_neighbors': [10,50,100],
             'weights':['uniform', 'distance'],
             'algorithm':['auto','ball_tree','kd_tree', 'brute'],
             'metric':['minkowski']}
grid = GridSearchCV(KNeighborsClassifier(),parameters,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['minkowski'], 'n_neighbors': [10, 50, 100],
                         'weights': ['uniform', 'distance']},
             scoring='f1_weighted', verbose=3)

In [16]:
print(grid.best_params_)

{'algorithm': 'auto', 'metric': 'minkowski', 'n_neighbors': 10, 'weights': 'distance'}

In [17]:
classifier = grid.cv_results_
# print(classifier)
print("The value for best parameter: ",format(grid.best_params_))

The value for best parameter:  {'algorithm': 'auto', 'metric': 'minkowski', 'n_neighbors': 10, 'weights': 'distance'}

In [18]:
table=pd.DataFrame.from_dict(classifier)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012415,0.005588,0.037326,0.005947,auto,minkowski,10,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.749046,0.770070,0.705612,0.867097,0.755313,0.769428,0.053342,5
1,0.009609,0.007858,0.028189,0.006854,auto,minkowski,10,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.829615,0.804628,0.732285,0.808775,0.718497,0.778760,0.044604,1
2,0.012733,0.006383,0.034409,0.006303,auto,minkowski,50,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.776290,0.717410,0.621589,0.783837,0.747667,0.729359,0.058759,17
3,0.015637,0.000726,0.027898,0.006154,auto,minkowski,50,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.808927,0.759881,0.732285,0.808775,0.698113,0.761596,0.043262,13
4,0.009374,0.007653,0.040616,0.007654,auto,minkowski,100,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.509779,0.525300,0.501410,0.501410,0.501410,0.507862,0.009302,21
5,0.015622,0.000002,0.023881,0.008424,auto,minkowski,100,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.808927,0.759881,0.727648,0.808775,0.715207,0.764088,0.039350,9
6,0.011731,0.006591,0.041420,0.004509,ball_tree,minkowski,10,uniform,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.749046,0.770070,0.705612,0.867097,0.755313,0.769428,0.053342,5
7,0.005952,0.006448,0.029420,0.002878,ball_tree,minkowski,10,distance,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.829615,0.804628,0.732285,0.808775,0.718497,0.778760,0.044604,1
8,0.013178,0.004045,0.034113,0.002274,ball_tree,minkowski,50,uniform,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.776290,0.717410,0.621589,0.783837,0.747667,0.729359,0.058759,17
9,0.010997,0.004369,0.029714,0.004370,ball_tree,minkowski,50,distance,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.808927,0.759881,0.732285,0.808775,0.698113,0.761596,0.043262,13
10,0.012283,0.005443,0.038197,0.006188,ball_tree,minkowski,100,uniform,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.509779,0.525300,0.501410,0.501410,0.501410,0.507862,0.009302,21
11,0.010996,0.004159,0.026081,0.004132,ball_tree,minkowski,100,distance,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.808927,0.759881,0.727648,0.808775,0.715207,0.764088,0.039350,9
12,0.008584,0.003826,0.039402,0.003990,kd_tree,minkowski,10,uniform,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.749046,0.770070,0.705612,0.867097,0.755313,0.769428,0.053342,5
13,0.013897,0.009626,0.025060,0.005231,kd_tree,minkowski,10,distance,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.829615,0.804628,0.732285,0.808775,0.718497,0.778760,0.044604,1
14,0.011737,0.000907,0.035076,0.003267,kd_tree,minkowski,50,uniform,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.776290,0.717410,0.621589,0.783837,0.747667,0.729359,0.058759,17
15,0.009542,0.005440,0.023321,0.004246,kd_tree,minkowski,50,distance,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.808927,0.759881,0.732285,0.808775,0.698113,0.761596,0.043262,13
16,0.010315,0.005607,0.042249,0.009765,kd_tree,minkowski,100,uniform,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.509779,0.525300,0.501410,0.501410,0.501410,0.507862,0.009302,21
17,0.014091,0.007222,0.033596,0.007866,kd_tree,minkowski,100,distance,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.808927,0.759881,0.727648,0.808775,0.715207,0.764088,0.039350,9
18,0.007128,0.007583,0.048097,0.017713,brute,minkowski,10,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.749046,0.770070,0.705612,0.867097,0.755313,0.769428,0.053342,5
19,0.010112,0.010868,0.031701,0.004158,brute,minkowski,10,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.829615,0.804628,0.732285,0.808775,0.718497,0.778760,0.044604,1
20,0.021441,0.022965,0.039287,0.006406,brute,minkowski,50,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.776290,0.717410,0.621589,0.783837,0.747667,0.729359,0.058759,17
21,0.009949,0.011235,0.029713,0.000889,brute,minkowski,50,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.808927,0.759881,0.732285,0.808775,0.698113,0.761596,0.043262,13
22,0.008726,0.007242,0.033995,0.013675,brute,minkowski,100,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.509779,0.525300,0.501410,0.501410,0.501410,0.507862,0.009302,21
23,0.014790,0.003933,0.016861,0.012848,brute,minkowski,100,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.808927,0.759881,0.727648,0.808775,0.715207,0.764088,0.039350,9

In [19]:
grid_pred=grid.predict(X_test)
grid_pred

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1])

In [20]:
from sklearn.metrics import confusion_matrix
con_mat=confusion_matrix(Y_test,grid_pred)
con_mat

array([[64, 21],
       [15, 34]], dtype=int64)

In [21]:
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,grid_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.81      0.75      0.78        85
           1       0.62      0.69      0.65        49

    accuracy                           0.73       134
   macro avg       0.71      0.72      0.72       134
weighted avg       0.74      0.73      0.73       134

In [22]:
from sklearn.metrics import roc_auc_score
roc = roc_auc_score(Y_test,grid_pred)
roc

0.7234093637454981

In [23]:
#to check the user input value 
Future_pred = grid.predict([[23,20000,0]])
print("Future Prediction ={}".format(Future_pred))

Future Prediction =[1]

C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(